routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Master
Route::group(['prefix' => 'master', 'as' => 'master.'], function () {
    // -- Master Companies
    Route::resource('/companies', App\Http\Controllers\CompaniesController::class)
        ->only(['index', 'create', 'store', 'edit', 'update']);
    Route::get('/companies/{company}/destroy', [App\Http\Controllers\CompaniesController::class, 'destroy'])->name('companies.destroy');
    Route::get('/companies/{company}/export', [App\Http\Controllers\CompaniesController::class, 'exportPdf'])->name('companies.export');

    // -- Master Companies
    Route::resource('/employees', App\Http\Controllers\EmployeesController::class)
        ->only(['index', 'create', 'store', 'edit', 'update']);
    Route::get('/employees/{employee}/destroy', [App\Http\Controllers\EmployeesController::class, 'destroy'])->name('employees.destroy');
});

app/Models/Master/Companies.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Companies extends Model
{
    use HasFactory;

    protected $table = 'companies';

    protected $fillable = [
        'nama',
        'email',
        'company'
    ];

    public function employees()
    {
        return $this->hasMany('App\Models\Master\Employees', 'company', 'id');
    }
}

app/Models/Master/Employees.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employees extends Model
{
    use HasFactory;

    protected $table = 'employees';

    protected $fillable = [
        'nama',
        'email',
        'logo',
        'website'
    ];

    public function companies()
    {
        return $this->hasOne('App\Models\Master\Companies', 'id', 'company');
    }
}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Eloquents\CompaniesEloquents;
use Illuminate\Http\Request;
use DataTables;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('master.companies.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['exists'] = 'new';

        return view('master.companies.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $validate = \Validator::make($request->all(), [
                'nama' => 'required',
                'email' => 'required|email',
                'file' => 'required|mimes:png|max:2048|dimensions:min_width=100,min_height=100',
                'website' => 'required',
            ]);

            if($validate->fails()){
                return redirect()->back()->withInput($request->input())->with('alert', [
                    'alert' => 'danger',
                    'icon' => 'attention',
                    'title' => 'Gagal ! ',
                    'text' => strip_tags($validate->errors()->first()),
                ]);
            }

            $data = CompaniesEloquents::storeOne($request);

            return redirect(route('master.companies.index'))->with('alert', [
                'alert' => 'success',
                'icon' => 'check',
                'title' => 'Berhasil ! ',
                'text' => 'Data berhasil ditambahkan'
            ]);
        } catch (\Exception $e) {
            return redirect()->back()->withInput($request->input())->with('alert', [
                'alert' => 'danger',
                'icon' => 'attention',
                'title' => 'Gagal ! ',
                'text' => $e->getMessage()
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Master\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function show(Companies $companies)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Master\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function edit($companies)
    {
        $companies = CompaniesEloquents::findById($companies);

        $data['exists'] = $companies;

        return view('master.companies.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Master\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $companies)
    {
        try {
            $validate = \Validator::make($request->all(), [
                'email' => 'email',
                'file' => 'mimes:png|max:2048|dimensions:min_width=100,min_height=100'
            ]);

            if($validate->fails()){
                return redirect()->back()->withInput($request->input())->with('alert', [
                    'alert' => 'danger',
                    'icon' => 'attention',
                    'title' => 'Gagal ! ',
                    'request' => $request,
                    'text' => strip_tags($validate->errors()->first()),
                ]);
            }

            $data = CompaniesEloquents::updateOne($request, $companies);

            return redirect(route('master.companies.index'))->with('alert', [
                'alert' => 'success',
                'icon' => 'check',
                'title' => 'Berhasil ! ',
                'text' => 'Data berhasil diubah'
            ]);
        } catch (\Exception $e) {
            return redirect()->back()->withInput($request->input())->with('alert', [
                'alert' => 'danger',
                'icon' => 'attention',
                'title' => 'Gagal ! ',
                'text' => $e->getMessage()
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Master\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function destroy($companies)
    {
        try {
            $check = CompaniesEloquents::findById($companies);

            if(!$check) {
                return redirect()->back()->withInput($request->input())->with('alert', [
                    'alert' => 'danger',
                    'icon' => 'attention',
                    'title' => 'Gagal ! ',
                    'text' => 'Data tidak ditemukan atau sudah dihapus'
                ]);
            }

            $check = CompaniesEloquents::destroyOne($check);

            return redirect(route('master.companies.index'))->with('alert', [
                'alert' => 'success',
                'icon' => 'check',
                'title' => 'Berhasil ! ',
                'text' => 'Data berhasil dihapus'
            ]);
        } catch (\Exception $e) {
            return redirect()->back()->withInput($request->input())->with('alert', [
                'alert' => 'danger',
                'icon' => 'attention',
                'title' => 'Gagal ! ',
                'text' => $e->getMessage(),
            ]);
        }
    }

    public function table(Request $request) {
        $data = CompaniesEloquents::getTableList($request);

        return $data;
    }

    public function exportPdf($companies) {
        $data = CompaniesEloquents::exportPdf($companies);

        return $data;
    }
}

resources/views/master/companies/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ $exists != "new" ? "Update" : "Create"}} Master Companies</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <!-- Row Form -->
                    <div class="row">
                        <div class="col">
                            <form id="form-action" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row mb-3">
                                    <div class="col">
                                        <div class="form-group">
                                            <img id="img-logo" class="img-fluid" src="" alt="" title="">
                                        </div>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="fl-logo">Logo</label>
                                            <input type="file" class="form-control" name="file" id="fl-logo" value="{{ old('file') }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="txt-nama">Nama</label>
                                            <input type="text" class="form-control" name="nama" id="txt-nama" required>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="txt-email">Email</label>
                                            <input type="email" class="form-control" name="email" id="txt-email" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="txt-website">Website</label>
                                            <input type="url" class="form-control" name="website" id="txt-website" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col">
                                        <div class="form-group d-flex">
                                            <button class="btn btn-primary ml-auto" type="submit">Simpan</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('script')
    <script>
        var exists = '{{ $exists }}';

        var renderComponents = () => {
            $('#txt-nama').val('{{ $exists != "new" ? $exists->nama : old("nama") }}')
            $('#txt-email').val('{{ $exists != "new" ? $exists->email : old("email") }}')
            $('#txt-website').val('{{ $exists != "new" ? $exists->website : old("website") }}')
            $('#form-action').attr('action', '{{ url("master/companies") }}'+'{{ $exists != "new" ? "/".$exists->id : "" }}')
            
            if (exists != "new") {
                $('#img-logo').attr('src', '{{ $exists != "new" ? asset("storage/logo/".$exists->logo) : "" }}')
                $('#form-action').prepend(`<input type="hidden" name="_method" value="PUT">`)
            }

            $('#fl-logo').change(function(){
                const file = this.files[0];
                console.log(file);
                if (file){
                    let reader = new FileReader();
                    reader.onload = function(event){
                        console.log(event.target.result);
                        $('#img-logo').attr('src', event.target.result);
                    }
                    reader.readAsDataURL(file);
                }
            });
        }

        $(document).ready(function() {
            renderComponents();
        })
    </script>
@endpush

resources/views/master/companies/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Master Companies</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <!-- Row Action -->
                    <div class="row mb-3">
                        <div class="col d-flex">
                            <div class="d-flex ml-auto">
                                <a href="{{ route('master.companies.create') }}" class="btn btn-primary">+ Tambah</a>
                            </div>
                        </div>
                    </div>

                    <!-- Row Table -->
                    <div class="row">
                        <div class="col">
                            <table id="datatable" class="table table-bordered table-responsive" style="overflow-x: auto">
                                <thead style="display:table-header-group">
                                    <tr>
                                        <th>#</th>
                                        <th>Logo</th>
                                        <th>Nama</th>
                                        <th>Email</th>
                                        <th>Website</th>
                                        <th>Employees</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script>
        var datatable = null

        var renderDatatable = () => {
            if(datatable) {
                datatable.destroy();
            }

            tableDatatable();
        }

        var tableDatatable = () => {
            datatable = $('#datatable').DataTable({
                scrollX: true,
                pagingType: "full_numbers",
                autoWidth: false,
                order: [],
                language: {
                    emptyTable: 'Tidak ada data yang tersedia',
                    info: 'Menampilkan _START_ sampai _END_ dari _TOTAL_ data',
                    infoEmpty: 'Menampilkan 0 sampai 0 dari 0 data',
                    infoFiltered: '(hasil filter dari _MAX_ total data)',
                    lengthMenu: 'Tampilkan _MENU_ data',
                    loadingRecords: 'Memuat...',
                    processing: 'Sedang Memproses...',
                    search: '',
                    searchPlaceholder: 'Cari..',
                    zeroRecords: 'Tidak ada data yang sesuai',
                    paginate: {
                        first: 'Awal',
                        last: 'Akhir',
                        next: 'Selanjutnya',
                        previous: 'Sebelumnya',
                    },
                },
                ajax: {
                    method: 'POST',
                    url: "{{ url('api/master/companies/table') }}",
                    data: function (data) {
                        //
                    }
                },
                columns: [
                    {
                        data: null,
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'logo',
                        name: 'logo',
                        orderable: false,
                        render: function (data, type, full, meta) {
                            data = data ? `<img src="{{ asset('storage/logo') }}/${data}" alt="" title="">` : null
                            return data
                        }
                    },
                    {
                        data: 'nama',
                        name: 'nama',
                        orderable: false,
                        render: function (data, type, full, meta) {
                            data = data ? data : null
                            return data
                        }
                    },
                    {
                        data: 'email',
                        name: 'email',
                        orderable: false,
                        render: function (data, type, full, meta) {
                            data = data ? data : null
                            return data
                        }
                    },
                    {
                        data: 'website',
                        name: 'website',
                        orderable: false,
                        render: function (data, type, full, meta) {
                            data = data ? data : null
                            return data
                        }
                    },
                    {
                        data: 'employees',
                        name: 'employees',
                        orderable: false,
                        render: function (data, type, full, meta) {
                            data = data ? data.length + ' Employees' : null
                            return data
                        }
                    },
                    {
                        data: 'action',
                        orderable: false,
                        searchable: false
                    }
                ],
                dom: 'lfrtip',
                "rowCallback": function(nRow, aData, iDisplayIndex) {
                    var oSettings = this.fnSettings();
                    $("td:first", nRow).html(oSettings._iDisplayStart + iDisplayIndex + 1);
                    return nRow;
                }
            });
        }

        var eventHandler = () => {
            $('table').on('click', '.btn-hapus', function(e) {
                Swal.fire({
                    title: 'Hapus Data ini?',
                    text: "Data yang dihapus tidak dapat dikembalikan!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#6c757d',
                    confirmButtonText: 'Batal',
                    cancelButtonColor: '#dc3545',
                    cancelButtonText: 'Hapus'
                }).then((result) => {
                    if (!result.value) {
                        window.location.href = $(this).attr('id')
                    }
                })
            })
        }

        var deleteData = () => {

        }

        $(document).ready(function() {
            renderDatatable();
            eventHandler();
        })
    </script>
@endpush